#!/bin/sh

CAPACITYFILE="/sys/class/power_supply/BAT0/capacity"
STATUSFILE="/sys/class/power_supply/BAT0/status"

fasm -d CAPACITYFILE=\"$CAPACITYFILE\" \
     -d STATUSFILE=\"$STATUSFILE\" \
     main.asm lowb
